dist: bionic
language: python
sudo: false
cache: pip

branches:
  only:
    - master
    - develop

matrix:
  include:
    - python: "3.5"

install:
  - pip install --ignore-installed --upgrade setuptools pip tox coveralls

script:
  - tox -vv

after_success:
  - coveralls

notifications:
  email: false
